export interface WeatherData {
  location: string;
  currentTemp: number;
  lowTemp: number;
  highTemp: number;
  condition: string; // e.g., "Rainy", "Sunny"
  comment: string; // The one-line comment
  newsLink?: string; // Link to a recommended news article
  sources?: { title: string; uri: string }[]; // For grounding attribution
  imageUrl?: string; // Base64 encoded image generated by AI
  imagePrompt?: string; // Description for generating the weather image
}

export enum LoadingState {
  IDLE = 'IDLE',
  LOADING = 'LOADING',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}